### ISSUE TITLE
Typos 1_0_StartingToDesignWithFreeCAD.pdf

### ISSUE THREAD

**Issue by hkienle** [macdroid53/LearningFreeCAD#1]
Thanks for the tutorial, very well done!

Typos:
- some lmited features -> some limited features
- , which do I use for the design I want to work on.  -> : So, which do I use for the design I want to work on?
- developers that to the end user -> developers than to the end user
- of to make life easier. -> of the developer's intent to make life easier.
- dimensions Part Design ->  dimensions in Part Design
- material that,, from -> material that, from
- of import more -> of importance for more
- At his point -> At this point
- it the lump. -> in the lump.

Other suggestions:
- Maybe mention that a unsaved document has a "*" after its name.
- Step 16: Auto constraints has to be enabled!?
- Step 17: No need to add vertical constraints because these are added automatically!?
- Step 17: Need to add "Fix the vertical distance" constraint with 12mm and 30mm! The picture shows these constraints.
- Broken link: https://github.com/macdroid53/LearningFreeCAD/blob/master/FreeCAD_Hole_Tool.pdf

**Comment by macdroid53** [comment]
Thank you!

Your note about the broken link triggered me to fix the links in the other documents as well. Forgot I had changed the naming scheme after putting in github.
