### ISSUE TITLE
Typos 1_1_FreeCAD_Hole_Tool

### ISSUE THREAD

**Issue by hkienle** [macdroid53/LearningFreeCAD#2]
- Broken link: https://github.com/macdroid53/LearningFreeCAD/blob/master/StartingToDesignWithFreeCAD.pdf
- create a ne sketch -> create a new sketch
- surface of the we -> surface of the Lump body, we
- by chaging -> by changing
- lot of optons -> lot of options

**Comment by macdroid53** [comment]
The link was fixed in the update to the file yesterday. Did you get the latest?

Will fix the typos shortly.

Thanks, I'm embarassed my proof reading was so lazy.

**Comment by hkienle** [comment]
Yes, the link works for me.

Proofreading ones own stuff is always tricky... :)

**Comment by macdroid53** [comment]
Actually just found a couple we both missed. :(
