### ISSUE TITLE
Drawing issues in TechDraw

### ISSUE THREAD

**Issue by thomaskilian** [macdroid53/LearningFreeCAD#4]
The cross section A-A (last page but also before) has a thick line in the middle which appears to be wrong. Either it should not be there or you have a thin dash-dot line here to indicate a symmetry.

**Comment by macdroid53** [comment]
The line is an artifact of the cylinder that was shown erroneously in earlier revs.

I have updated with a later version of 0.19 and updated the pdf.

Thanks!

**Comment by thomaskilian** [comment]
Also thanks for the help on the forum :-)

**Comment by macdroid53** [comment]
You're welcome!
